In [62]:
# Create a list containing the names: baby_names
baby_names = ['Ximena', 'Aliza', 'Ayden', 'Calvin']

# Extend baby_names with 'Rowen' and 'Sandeep'
baby_names.extend(['Rowen', 'Sandeep'])

# Print baby_names
print(baby_names)

# Find the position of 'Aliza': position
position = baby_names.index('Aliza')

# Remove 'Aliza' from baby_names
baby_names.pop(position)

# Print baby_names
print(baby_names)

['Ximena', 'Aliza', 'Ayden', 'Calvin', 'Rowen', 'Sandeep']
['Ximena', 'Ayden', 'Calvin', 'Rowen', 'Sandeep']

In [64]:
import pandas as pd
import numpy as np

records=pd.read_csv('../datasets/baby_names.csv', header=0)
records['NAME'] = records['NAME'].str.upper() 
print(records)

BRITH_YEAR  GENDER            ETHNICTY       NAME  COUNT  RANK
0            2011  FEMALE            HISPANIC  GERALDINE     13    75
1            2011  FEMALE            HISPANIC        GIA     21    67
2            2011  FEMALE            HISPANIC     GIANNA     49    42
3            2011  FEMALE            HISPANIC    GISELLE     38    51
4            2011  FEMALE            HISPANIC      GRACE     36    53
...           ...     ...                 ...        ...    ...   ...
13957        2014    MALE  WHITE NON HISPANIC     YOUSEF     18    94
13958        2014    MALE  WHITE NON HISPANIC    YOUSSEF     24    88
13959        2014    MALE  WHITE NON HISPANIC      YUSUF     16    96
13960        2014    MALE  WHITE NON HISPANIC    ZACHARY     90    39
13961        2014    MALE  WHITE NON HISPANIC        ZEV     49    65

[13962 rows x 6 columns]

In [66]:
# Create the empty list: baby_names
baby_names = []

# Loop over records 
for row in np.array(records):
    # Add the name to the list
    baby_names.append(row[3])
    
# Sort the names in alphabetical order
for name in sorted(baby_names):
    # Print each name
    print(name)

ERRY
PESSY
PESSY
PESSY
PESSY
PESSY
PESSY
PESSY
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PETER
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PEYTON
PHILIP
PHILIP
PHILIP
PHILIP
PHILIP
PHILIP
PHILIP
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOEBE
PHOENIX
PHOENIX
PHOENIX
PINCHAS
PINCHAS
PINCHAS
PINCHAS
PINCHAS
PINCHAS
PINCHAS
PINCHUS
PINCHUS
PINCHUS
PINCHUS
PINCHUS
PINCHUS
PIPER
PIPER
PIPER
PIPER
PIPER
PIPER
PIPER
POLINA
POPPY
POPPY
PRECIOUS
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRESTON
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCE
PRINCESS
PRINCESS
PRINCESS
PRINCESS
PRINCESS
PRINCESS
PRINCETON
PRISCILLA
QUEENA
QUEENIE
QUEENIE
QUEENIE
QUEENIE
QUEENIE
QUEENIE
QUEENIE
QUINCY
QUINCY
QUINCY
QUINCY
QUINCY
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
QUINN
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RACHEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAFAEL
RAINA
RAINA
RAINA
RAINA
RAINA
RAINA
RAIZEL
RAIZEL
RAIZEL
RAIZEL
RAIZEL
RAIZEL
RAIZEL
RAIZY
RAIZY
RAIZY
RAIZY
RAIZY
RAIZY
RAIZY
RANDY
RANDY
RANDY
RANDY
RANDY
RANDY
RANDY
RAPHAEL
RAPHAEL
RAPHAEL
RAPHAEL
RAPHAEL
RAPHAEL
RAPHAEL
RAQUEL
RAQUEL
RAQUEL
RAQUEL
RAQUEL
RAQUEL
RAUL
RAUL
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYAN
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYMOND
RAYYAN
RAYYAN
REAGAN
REAGAN
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REBECCA
REED
REED
REED
REED
REED
REED
REEM
REESE
REESE
REESE
REESE
REESE
REESE
REESE
REHAN
REHAN
REHAN
REID
REID
REID
REID
REID
REID
REID
REIZY
RENA
RENEE
RENEE
RENEE
RENEE
RENEE
REUBEN
REUVEN
RHYS
RHYS
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICARDO
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICHARD
RICKY
RICKY
RICKY
RICKY
RICKY
RICKY
RICKY
RIFKA
RIFKA
RIFKA
RIFKA
RIFKY
RIFKY
RIFKY
RIFKY
RIFKY
RIFKY
RIFKY
RIHANNA
RIHANNA
RIHANNA
RIHANNA
RIHANNA
RIHANNA
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RILEY
RIVKA
RIVKA
RIVKA
RIVKA
RIVKA
RIVKA
RIVKA
RIVKY
RIVKY
RIVKY
RIVKY
RIVKY
RIVKY
RIVKY
RIYA
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERT
ROBERTO
ROBERTO
ROBERTO
ROBERTO
ROBERTO
ROBERTO
ROBERTO
ROCCO
ROCCO
ROCCO
ROCCO
ROCCO
ROCCO
ROCCO
ROCHEL
ROCHEL
ROCHEL
ROCHEL
ROCHEL
ROCHEL
ROCHEL
RODNEY
RODNEY
RODNEY
RODNEY
RODRIGO
RODRIGO
RODRIGO
RODRIGO
RODRIGO
RODRIGO
RODRIGO
ROGER
ROGER
ROGER
ROGER
ROHAN
ROHAN
ROHAN
ROHAN
ROHAN
ROHAN
ROHAN
ROIZA
ROIZY
ROIZY
ROIZY
ROIZY
ROIZY
ROIZY
ROMAN
ROMAN
ROMAN
ROMAN
ROMAN
ROMAN
ROMAN
ROMAN
ROMAN
ROMAN
ROMEO
ROMEO
ROMEO
ROMEO
ROMEO
ROMEO
ROMEO
ROMY
RONALD
RONAN
RONAN
RONAN
RORY
RORY
RORY
ROSA
ROSA
ROSA
ROSA
ROSA
ROSA
ROSA
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSE
ROSELYN
ROSELYN
ROSELYN
ROSELYN
ROSELYN
ROSIE
ROWAN
ROWAN
ROWAN
ROWAN
ROWAN
ROWAN
ROWAN
ROWAN
ROY
ROY
ROY
ROYCE
ROYCE
ROYCE
ROYCE
RUBEN
RUBEN
RUBEN
RUBEN
RUBEN
RUBEN
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUBY
RUCHEL
RUCHY
RUCHY
RUCHY
RUCHY
RUCHY
RUCHY
RUCHY
RUTH
RUTH
RUTH
RUTH
RUTH
RUTH
RUTH
RUTH
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYAN
RYDER
RYDER
RYDER
RYDER
RYDER
RYDER
RYDER
SABINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SABRINA
SADE
SADE
SADE
SADE
SADIE
SADIE
SADIE
SADIE
SADIE
SADIE
SADIE
SADIE
SADIE
SADIE
SADIE
SAFA
SAGE
SAGE
SAIGE
SALMA
SALMA
SALMA
SALMA
SALMA
SALMA
SALMA
SALOME
SALOME
SALVATORE
SALVATORE
SALVATORE
SALVATORE
SALVATORE
SALVATORE
SALVATORE
SAM
SAM
SAM
SAM
SAM
SAM
SAM
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMANTHA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMARA
SAMI
SAMIR
SAMIR
SAMIR
SAMIR
SAMIR
SAMIR
SAMIR
SAMIR
SAMIR
SAMIRA
SAMIYA
SAMIYA
SAMIYA
SAMIYA
SAMIYAH
SAMIYAH
SAMIYAH
SAMIYAH
SAMIYAH
SAMIYAH
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SAMUEL
SANAA
SANAA
SANAA
SANAA
SANAA
SANAA
SANAA
SANAI
SANAI
SANAI
SANAI
SANAI
SANAI
SANAI
SANDRA
SANIYA
SANIYA
SANIYA
SANIYA
SANIYAH
SANIYAH
SANIYAH
SANIYAH
SANIYAH
SANIYAH
SANIYAH
SANTIAGO
SANTIAGO
SANTIAGO
SANTIAGO
SANTIAGO
SANTIAGO
SANTIAGO
SANTINO
SANTINO
SANTINO
SANTINO
SANTINO
SANTINO
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARA
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAH
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARAI
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARIAH
SARINA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SASHA
SAUL
SAUL
SAVANNA
SAVANNA
SAVANNA
SAVANNA
SAVANNA
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVANNAH
SAVION
SAWYER
SAWYER
SCARLET
SCARLET
SCARLET
SCARLET
SCARLET
SCARLET
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SCARLETT
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEBASTIAN
SEKOU
SEKOU
SEKOU
SEKOU
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELENA
SELINA
SELINA
SELINA
SELINA
SELINA
SELINA
SELINA
SELMA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENA
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERENITY
SERGIO
SERGIO
SERGIO
SERGIO
SERGIO
SERGIO
SERGIO
SETH
SETH
SETH
SETH
SETH
SHAINA
SHAINA
SHAINA
SHAINA
SHAINA
SHAINA
SHAINA
SHAINDEL
SHAINDEL
SHAINDEL
SHAINDEL
SHAINDEL
SHAINDEL
SHAINDY
SHAINDY
SHAINDY
SHAINDY
SHAINDY
SHAINDY
SHAINDY
SHALOM
SHALOM
SHALOM
SHALOM
SHALOM
SHALOM
SHALOM
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANE
SHANIA
SHANIA
SHANIA
SHANIA
SHANIA
SHANIYA
SHANIYA
SHANIYA
SHANIYA
SHARON
SHARON
SHARON
SHARON
SHARON
SHARON
SHARON
SHAUL
SHAUL
SHAUL
SHAUL
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAWN
SHAYA
SHAYA
SHAYA
SHAYA
SHAYA
SHAYA
SHAYA
SHAYAAN
SHAYAN
SHAYAN
SHAYLA
SHAYLA
SHAYNA
SHEA
SHEA
SHEA
SHEA
SHEA
SHEA
SHEA
SHERLYN
SHERLYN
SHERLYN
SHERLYN
SHERLYN
SHERLYN
SHERLYN
SHERRY
SHEVY
SHEVY
SHEVY
SHEVY
SHIA
SHIA
SHIA
SHIA
SHIA
SHIA
SHIA
SHIFRA
SHIFRA
SHIFRA
SHIFRA
SHIFRA
SHIFRA
SHIFRA
SHILOH
SHILOH
SHILOH
SHILOH
SHILOH
SHIMON
SHIMON
SHIMON
SHIMON
SHIMON
SHIMON
SHIMON
SHIRA
SHIRA
SHIRA
SHIRA
SHIRA
SHIRA
SHIRA
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHIRLEY
SHLOIME
SHLOIME
SHLOIME
SHLOIME
SHLOIME
SHLOIME
SHLOIME
SHLOIMY
SHLOIMY
SHLOIMY
SHLOIMY
SHLOIMY
SHLOIMY
SHLOIMY
SHLOMA
SHLOME
SHLOME
SHLOME
SHLOME
SHLOME
SHLOME
SHLOME
SHLOMO
SHLOMO
SHLOMO
SHLOMO
SHLOMO
SHLOMO
SHLOMO
SHMIEL
SHMIEL
SHMIEL
SHMIEL
SHMIEL
SHMIEL
SHMIEL
SHMUEL
SHMUEL
SHMUEL
SHMUEL
SHMUEL
SHMUEL
SHMUEL
SHNEUR
SHNEUR
SHNEUR
SHNEUR
SHNEUR
SHNEUR
SHOLOM
SHOLOM
SHOLOM
SHOLOM
SHOLOM
SHOLOM
SHOLOM
SHOSHANA
SHOSHANA
SHOSHANA
SHOSHANA
SHOSHANA
SHOSHANA
SHOSHANA
SHRAGA
SHRAGA
SHREYA
SHULEM
SHULEM
SHULEM
SHULEM
SHULEM
SHULEM
SHULEM
SIDNEY
SIDNEY
SIDNEY
SIDNEY
SIENA
SIENA
SIENA
SIENA
SIENA
SIENA
SIENA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SIENNA
SILAS
SILAS
SILAS
SILAS
SILAS
SILAS
SILAS
SIMA
SIMA
SIMA
SIMA
SIMA
SIMA
SIMA
SIMCHA
SIMCHA
SIMCHA
SIMCHA
SIMCHA
SIMCHA
SIMCHA
SIMI
SIMI
SIMI
SIMI
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMON
SIMONE
SIMONE
SIMONE
SIMONE
SIMONE
SIMONE
SIMONE
SINCERE
SINCERE
SINCERE
SINCERE
SINCERE
SINCERE
SINCERE
SKYE
SKYE
SKYE
SKYE
SKYE
SKYE
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLA
SKYLAH
SKYLAH
SKYLAH
SKYLAH
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLAR
SKYLER
SKYLER
SKYLER
SKYLER
SKYLER
SLOANE
SLOANE
SLOANE
SLOANE
SLOANE
SLOANE
SLOANE
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOFIA
SOLOMON
SOLOMON
SOLOMON
SOLOMON
SOLOMON
SOLOMON
SOLOMON
SONIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIA
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SOPHIE
SORAYA
SORAYA
SORAYA
SORAYA
SPENCER
SPENCER
SPENCER
SPENCER
SPENCER
SPENCER
SPENCER
STACEY
STACY
STACY
STACY
STACY
STACY
STACY
STANLEY
STANLEY
STANLEY
STANLEY
STANLEY
STANLEY
STANLEY
STANLEY
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STELLA
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANIE
STEPHANY
STEPHANY
STEPHANY
STEPHANY
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEPHEN
STEVE
STEVE
STEVE
STEVE
STEVE
STEVE
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
STEVEN
SUBHAN
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUMMER
SUNNY
SURI
SURI
SURI
SURI
SURI
SURI
SURY
SURY
SURY
SURY
SURY
SURY
SURY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYDNEY
SYED
SYED
SYED
SYED
SYED
SYED
SYED
SYEDA
SYEDA
SYEDA
SYEDA
SYEDA
SYEDA
SYEDA
SYLVIA
SYLVIA
SYLVIA
SYLVIA
SYLVIA
SYLVIA
SYLVIA
SYLVIA
SYLVIA
SYLVIE
SYLVIE
SYMPHONY
SYMPHONY
SYMPHONY
SYMPHONY
TABITHA
TABITHA
TABITHA
TABITHA
TALIA
TALIA
TALIA
TALIA
TALIA
TALIA
TALIA
TALIA
TALIA
TAMAR
TAMAR
TAMAR
TAMAR
TAMAR
TAMAR
TAMAR
TAMIA
TAMIA
TAMIA
TAMIA
TAMIA
TAMIA
TANISHA
TANISHA
TANISHA
TANISHA
TARAJI
TARAJI
TARAJI
TARAJI
TASNIM
TATIANA
TATIANA
TATIANA
TATIANA
TATIANA
TATIANA
TATIANA
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TAYLOR
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TENZIN
TERRELL
TERRELL
TERRELL
TERRELL
TERRELL
TERRENCE
TERRENCE
TERRENCE
TERRENCE
TERRENCE
TERRY
TERRY
TERRY
TERRY
TESS
TESSA
TESSA
TESSA
TESSA
TESSA
TESSA
TESSA
THEA
THEO
THEO
THEO
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THEODORE
THIAGO
THIAGO
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
THOMAS
TIANA
TIANA
TIANA
TIANA
TIANA
TIANA
TIANA
TIANA
TIANA
TIANA
TIANA
TIANNA
TIANNA
TIANNA
TIANNA
TIANNA
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIFFANY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TIMOTHY
TINA
TINA
TINA
TINA
TINA
TINA
TOBY
TOBY
TOBY
TOBY
TOBY
TOBY
TOBY
TOMAS
TOMAS
TOMAS
TOMAS
TOMAS
TOMAS
TONY
TONY
TONY
TONY
TONY
TONY
TORI
TORI
TORI
TORI
TORI
TORI
TOVA
TRANY
TRANY
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRAVIS
TRINITY
TRINITY
TRINITY
TRINITY
TRINITY
TRINITY
TRINITY
TRINITY
TRINITY
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TRISTAN
TROY
TROY
TROY
TROY
TROY
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TYLER
TZIPORA
TZIPORA
TZIPORA
TZIPORA
TZIPORA
TZIPORA
TZIPORA
TZIPORAH
TZIPORAH
TZIPORAH
TZIPORAH
TZIPORAH
TZIPPY
TZIPPY
TZIPPY
TZIPPY
TZIVIA
TZIVIA
TZIVIA
TZIVIA
TZIVIA
TZVI
TZVI
TZVI
TZVI
TZVI
TZVI
TZVI
URIEL
URIEL
URIEL
URIEL
URIEL
URIEL
URIEL
USHER
USHER
USHER
USHER
USHER
USHER
USHER
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINA
VALENTINO
VALERIA
VALERIA
VALERIA
VALERIA
VALERIA
VALERIA
VALERIA
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERIE
VALERY
VALERY
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VANESSA
VERA
VERA
VERA
VERA
VERA
VERA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONICA
VERONIKA
VERONIKA
VERONIKA
VERONIKA
VICKY
VICKY
VICKY
VICKY
VICKY
VICKY
VICKY
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTOR
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VICTORIA
VIHAAN
VIHAAN
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENT
VINCENZO
VINCENZO
VINCENZO
VINCENZO
VINCENZO
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLET
VIOLETA
VIRGINIA
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIAN
VIVIANA
VIVIANA
VIVIANA
VIVIANA
VIVIANA
VIVIENNE
VIVIENNE
VIVIENNE
VIVIENNE
VIVIENNE
VIVIENNE
VIVIENNE
WALTER
WALTER
WENDY
WENDY
WENDY
WENDY
WENDY
WENDY
WENDY
WENDY
WENDY
WENDY
WENDY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESLEY
WESTON
WILLA
WILLA
WILLA
WILLA
WILLA
WILLA
WILLA
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILLIAM
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WILSON
WINNIE
WINNIE
WINNIE
WINNIE
WINNIE
WINNIE
WINNIE
WINSTON
WINSTON
WINSTON
WINSTON
WINTER
WOLF
WOLF
WYATT
WYATT
WYATT
WYATT
WYATT
WYATT
WYATT
WYATT
WYNTER
WYNTER
WYNTER
XANDER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XAVIER
XIMENA
XIMENA
XIMENA
XIMENA
XIMENA
XIMENA
XIMENA
XIN
XIN
XIN
XIN
XIN
YAAKOV
YAAKOV
YAAKOV
YAAKOV
YAAKOV
YAAKOV
YAAKOV
YACHET
YACHET
YACHET
YACHET
YADIEL
YADIEL
YADIEL
YADIEL
YADIEL
YADIEL
YADIEL
YAEL
YAEL
YAEL
YAEL
YAEL
YAEL
YAEL
YAEL
YAHIR
YAHIR
YAHIR
YAHIR
YAHIR
YAHIR
YAHIR
YAHYA
YAIR
YAIR
YAIR
YAIR
YAKOV
YAKOV
YAKOV
YAKOV
YAKOV
YAKOV
YAKOV
YAMILET
YAMILET
YAMILET
YAMILET
YAMILETH
YAMILETH
YANDEL
YANDEL
YANDEL
YANDEL
YANDEL
YANDEL
YANIEL
YANIEL
YANIEL
YANIEL
YANKY
YARA
YARETZI
YARETZI
YARETZI
YARETZI
YARETZI
YARETZI
YARETZI
YARIEL
YARIEL
YARIEL
YARIEL
YARIEL
YARIEL
YARIEL
YASEEN
YASEEN
YASEEN
YASEEN
YASEEN
YASMIN
YASMIN
YASMINA
YASMINE
YASMINE
YASMINE
YASMINE
YASMINE
YASSIN
YECHEZKEL
YECHEZKEL
YECHEZKEL
YECHEZKEL
YECHEZKEL
YECHIEL
YECHIEL
YECHIEL
YECHIEL
YECHIEL
YECHIEL
YECHIEL
YEHOSHUA
YEHOSHUA
YEHOSHUA
YEHOSHUA
YEHOSHUA
YEHOSHUA
YEHOSHUA
YEHUDA
YEHUDA
YEHUDA
YEHUDA
YEHUDA
YEHUDA
YEHUDA
YEHUDAH
YEHUDAH
YEHUDAH
YEHUDAH
YEHUDIS
YEHUDIS
YEHUDIS
YEHUDIS
YEHUDIS
YEHUDIS
YEHUDIS
YERIK
YERIK
YERIK
YERIK
YESENIA
YESHAYA
YIDA
YIDA
YIDA
YIDA
YIDEL
YIDEL
YIDEL
YIDEL
YIDEL
YIDES
YIDES
YIDES
YIDES
YIDES
YIDES
YIDES
YISRAEL
YISRAEL
YISRAEL
YISRAEL
YISRAEL
YISRAEL
YISROEL
YISROEL
YISROEL
YISROEL
YISROEL
YISROEL
YISROEL
YITTA
YITTY
YITTY
YITTY
YITTY
YITTY
YITTY
YITTY
YITZCHAK
YITZCHAK
YITZCHAK
YITZCHAK
YITZCHAK
YITZCHAK
YITZCHAK
YITZCHOK
YITZCHOK
YITZCHOK
YITZCHOK
YITZCHOK
YITZCHOK
YITZCHOK
YOCHEVED
YOCHEVED
YOCHEVED
YOCHEVED
YOCHEVED
YOCHEVED
YOCHEVED
YOEL
YOEL
YOEL
YOEL
YOEL
YOEL
YOEL
YONA
YONAH
YONAH
YONAH
YONAH
YOSEF
YOSEF
YOSEF
YOSEF
YOSEF
YOSEF
YOSEF
YOSSI
YOSSI
YOSSI
YOUSEF
YOUSEF
YOUSEF
YOUSEF
YOUSEF
YOUSEF
YOUSEF
YOUSSEF
YOUSSEF
YOUSSEF
YOUSSEF
YOUSSEF
YOUSSEF
YOUSSEF
YU
YU
YU
YU
YUSUF
YUSUF
YUSUF
YUSUF
ZACHARIAH
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZACHARY
ZAHARA
ZAHARA
ZAHARA
ZAHARA
ZAHIR
ZAHRA
ZAHRA
ZAHRA
ZAHRA
ZAHRA
ZAHRA
ZAIDEN
ZAIN
ZAIN
ZAIN
ZAIN
ZAIN
ZAIN
ZAIN
ZAIN
ZAINAB
ZAINAB
ZAINAB
ZAINAB
ZAINAB
ZAINAB
ZAINAB
ZAIRE
ZAIRE
ZAIRE
ZAIRE
ZAIRE
ZAIRE
ZAIRE
ZALMEN
ZALMEN
ZALMEN
ZALMEN
ZALMEN
ZALMEN
ZAMIR
ZANE
ZANIYAH
ZANIYAH
ZANIYAH
ZANIYAH
ZANIYAH
ZANIYAH
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARA
ZARIA
ZARIA
ZARIA
ZARIA
ZARIAH
ZARIAH
ZARIAH
ZARIAH
ZARIAH
ZARIAH
ZAYAN
ZAYAN
ZAYAN
ZAYAN
ZAYAN
ZAYAN
ZAYAN
ZAYDEN
ZAYDEN
ZAYDEN
ZAYDEN
ZELDA
ZELDA
ZENDAYA
ZEV
ZEV
ZEV
ZEV
ZEV
ZEV
ZEV
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZION
ZISSY
ZISSY
ZISSY
ZISSY
ZISSY
ZISSY
ZISSY
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOE
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOEY
ZOYA
ZURI
ZURI
ZURI
ZURI
ZURI
ZURI
ZURI
ZYAIRE
ZYAIRE
ZYAIRE
ZYAIRE

In [68]:
"""Q: Which data type would you use if you wanted your data to be immutable and ordered?
A: Tuple"""

'Q: Which data type would you use if you wanted your data to be immutable and ordered?\nA: Tuple'

In [69]:
record_s=np.array(sorted(np.array(records), key=lambda record_: [record_[4]]))
girl_names =record_s[(record_s[:, 1]=='FEMALE') ][:68, 3]
boy_names =record_s[(record_s[:, 1]=='MALE') ][:68, 3]

In [70]:
# Pair up the girl and boy names: pairs
pairs = list(zip(girl_names, boy_names))

# Iterate over pairs
for idx, pair in enumerate(pairs):
    # Unpack pair: girl_name, boy_name
    girl_name, boy_name = pair
    # Print the rank and names associated with each rank
    print('Rank {}: {} and {}'.format(idx, girl_name, boy_name))

Rank 0: HAZEL and CODY
Rank 1: IRIS and EASON
Rank 2: ISABELA and HAYDEN
Rank 3: JAYDA and ISHAAN
Rank 4: JAYLYN and LOUIS
Rank 5: KATELYNN and MILES
Rank 6: KAYLEIGH and OLIVER
Rank 7: KYLEE and RAYAN
Rank 8: LEA and SHAWN
Rank 9: LEYLA and XAVIER
Rank 10: MARILYN and ZAYAN
Rank 11: MARISOL and ALIJAH
Rank 12: NANCY and ALVIN
Rank 13: NATHALIA and ANGEL
Rank 14: PAOLA and BRYAN
Rank 15: REBECCA and CHRIS
Rank 16: ROSA and CODY
Rank 17: SARIAH and COREY
Rank 18: SASHA and DERRICK
Rank 19: SAVANNA and DEVON
Rank 20: STACY and DONOVAN
Rank 21: VERONICA and EDWARD
Rank 22: ANGELICA and GEORGE
Rank 23: ARIELA and HASSAN
Rank 24: ATARA and ISHMAEL
Rank 25: AUBREY and JAHEIM
Rank 26: AUTUMN and MAKAI
Rank 27: AYLA and MARQUIS
Rank 28: BIANCA and MILES
Rank 29: CELIA and NANA
Rank 30: CHAVY and NIGEL
Rank 31: CORA and QUINCY
Rank 32: DALIA and RICARDO
Rank 33: FRIMET and RODNEY
Rank 34: GIOVANNA and STEPHEN
Rank 35: IDY and TERRELL
Rank 36: ILANA and ALDO
Rank 37: IZABELLA and ALLAN
Rank 38: JULIE and ALVIN
Rank 39: LEILA and ANDRE
Rank 40: LONDON and ARTURO
Rank 41: MIRI and BRYCE
Rank 42: NICOLETTE and ELVIS
Rank 43: QUINN and GIOVANI
Rank 44: SHEVY and JANIEL
Rank 45: SIMI and JEANCARLOS
Rank 46: TZIPORAH and JESSE
Rank 47: TZIPPY and LARRY
Rank 48: YASMINE and MARLON
Rank 49: AIZA and SHANE
Rank 50: ALEXA and STEPHEN
Rank 51: ALISHA and STEVE
Rank 52: ANGIE and TAYLOR
Rank 53: ANNABELLE and TOMAS
Rank 54: BONNIE and YAIR
Rank 55: HELEN and YANIEL
Rank 56: KATE and ASHTON
Rank 57: LEELA and AUGUSTUS
Rank 58: MAGGIE and AYDEN
Rank 59: MEGAN and BENNETT
Rank 60: RENEE and BERISH
Rank 61: TANISHA and BRYCE
Rank 62: AISHA and CADEN
Rank 63: CHEYENNE and CALVIN
Rank 64: ERIN and DEREK
Rank 65: JALIYAH and ELLIS
Rank 66: JULIA and KENNETH
Rank 67: KAI and LEV

In [71]:
# Create the normal variable: normal
normal = 'simple'

# Create the mistaken variable: error
error = 'trailing comma',

# Print the types of the variables
print(type(normal))
print(type(error))

<class 'str'>
<class 'tuple'>

In [72]:

baby_names_2011=set(records[records['BRITH_YEAR']==2011]['NAME'])
baby_names_2014=set(records[records['BRITH_YEAR']==2014]['NAME'])

In [73]:
# Find the union: all_names
all_names = baby_names_2011.union(baby_names_2014)

# Print the count of names in all_names
print(len(all_names))

# Find the intersection: overlapping_names
overlapping_names = baby_names_2011.intersection(baby_names_2014)

# Print the count of names in overlapping_names
print(len(overlapping_names))

1460
987

In [74]:
# Create the empty set: baby_names_2011
baby_names_2011 = set()
#print(records)
# Loop over records and add the names from 2011 to the baby_names_2011 set
for row in np.array(records):
    # Check if the first column is '2011'
    if row[0] == 2011:
        # Add the fourth column to the set
        baby_names_2011.add(row[3])

# Find the difference between 2011 and 2014: differences
differences = baby_names_2011.difference(baby_names_2014)

# Print the differences
print(differences)

{'CRISTINA', 'MALCOLM', 'JIA', 'CHRISTY', 'HAYLEY', 'ISIS', 'INGRID', 'ROYCE', 'BYRON', 'MIAH', 'SHNEUR', 'KRYSTAL', 'FARHAN', 'ELIANNY', 'SADE', 'RIHANNA', 'DIYA', 'JENCARLOS', 'GERALDINE', 'FERNANDA', 'LUZ', 'JAYLYN', 'CRISTOFER', 'KAYLEIGH', 'KAELYN', 'JAMEL', 'KAMERON', 'NICOLETTE', 'KEITH', 'SHANIA', 'MAKSIM', 'RAQUEL', 'SANIYA', 'CHAD', 'KELVIN', 'LEONEL', 'JOHNATHAN', 'YAIR', 'ABDIEL', 'DERECK', 'MAURICE', 'JANUEL', 'RODNEY', 'ALIJAH', 'JASMIN', 'ZYAIRE', 'DULCE', 'SORAYA', 'BREINDY', 'LARRY', 'YU', 'MARISOL', 'KIYAN', 'EDDIE', 'TARAJI', 'GUSTAVO', "AMAR'E", 'SHEVY', 'ARIELA', 'NATASHA', 'TAMIA', 'SAVANNA', 'HEIDY', 'TZIVIA', 'NATALY', 'ELIANNA', 'AMROM', 'MILENA', 'JERMAINE', 'ARIANNY', 'DWAYNE', 'ALISSON', 'YAMILET', 'JACKY', 'HALEY', 'TABITHA', 'TZIPPY', 'OUSMANE', 'TINA', 'MAKAI', 'ANALIA', 'ELISE', 'LESLEY', 'JAMIE', 'JANIYA', 'ALEC', 'STACY', 'YIDA', 'YACHET', 'MICHAL', 'CHEYENNE', 'ALFREDO', 'MILEY', 'ISHAAN', 'SIDNEY', 'JAHMIR', 'JAMAL', 'YONAH', 'IDY', 'SAMIYAH', 'CRISTOPHER', 'ILAN', 'DANA', 'KAMIYAH', 'SEKOU', 'TANISHA', 'AIMEE', 'MAURICIO', 'BRITNEY', 'KALIYAH', 'ANGELY', 'JOHANN', 'ARMANDO', 'DENISE', 'CASEY', 'TROY', 'ISHMAEL', 'ABDUL', 'JEREMIAS', 'JAIME', 'FREDDY', 'ZAHRA', 'BRIANNY', 'YEHUDAH', 'ALDO', 'KENYA', 'RENEE', 'KACPER', 'ROGER', 'JASLENE', 'JANIEL', 'JAZMINE', 'CASSANDRA', 'SIMI', 'COREY', 'SYMPHONY', 'GIOVANNY', 'SHAUL', 'VERONIKA', 'YANIEL', 'KATHRYN', 'SCARLET', 'XIN', 'GIOVANI', 'KYMANI', 'MAXIMO', 'LEELA', 'ROSELYN', 'NIGEL', 'JAMIR', 'AMANI', 'YECHEZKEL', 'ZAHARA', 'KATELYNN', 'ISIAH', 'FINLEY', 'GITTEL', 'CODY', 'HADASSA', 'NIKOLAS', 'NOEMI', 'CARMINE', 'AHRON', 'DAMARIS', 'SAMIYA', 'ESTRELLA', 'ARTURO', 'SHANIYA', 'ILANA', 'JOHANNA', 'BATYA', 'PAOLA', 'MIRI', 'CHRISTINE', 'ANIKA', 'VIVIANA', 'FRANKLIN', 'AUGUSTUS', 'ANNABEL', 'ISABELA', 'PERLA', 'KEILY', 'RIFKA', 'STEPHANY', 'JELANI', 'ALYSON', 'MARQUIS', 'ZALMEN', 'TERRENCE', 'PRINCESS', 'JAHEIM', 'NANCY', 'DALIA', 'ELLIANA', 'TERRELL', 'ESHAL', 'GRETA', 'NANA', 'JEANCARLOS', 'AARAV', 'BONNIE', 'LAMAR', 'JULIEN', 'JANIYAH', 'ESSENCE', 'JAELYNN', 'ZARIA', 'JALIYAH', 'TERRY', 'KAILYN', 'DEVON', 'DERRICK', 'ADITYA', 'NATHALIA', 'ASHLY', 'TOMAS', 'DARIUS', 'NEHEMIAH', 'YERIK'}

In [75]:
df_2012_female=records[ (records['GENDER']=='FEMALE') & (records['BRITH_YEAR']==2012) ].loc[:, ['NAME','RANK']]

female_baby_names_2012= dict(zip(df_2012_female.RANK, df_2012_female.NAME))

print(female_baby_names_2012)
# Create an empty dictionary: names_by_rank
names_by_rank={}

# Loop over the girl names
for rank, name in female_baby_names_2012.items():
    # Add each name to the names_by_rank dictionary using rank as the key
    names_by_rank[rank]=name
    
# Sort the names_by_rank dict by rank in descending order and slice the first 10 items
for rank in sorted(names_by_rank, reverse=True)[0:10]:
    # Print each item
    print(names_by_rank[rank])

{44: 'RIVKY', 26: 'JULIA', 43: 'TOBY', 37: 'MALKY', 19: 'ABIGAIL', 25: 'ZOE', 42: 'PENELOPE', 39: 'MALKA', 33: 'SHAINDY', 36: 'MADISON', 35: 'GITTY', 32: 'STELLA', 41: 'MADELINE', 7: 'CHAYA', 38: 'EVA', 18: 'ELIZABETH', 30: 'GRACE', 34: 'FAIGY', 14: 'SARA', 45: 'NICOLE', 20: 'ALEXANDRA', 12: 'EMILY', 29: 'HANNAH', 1: 'EMMA', 40: 'ALEXA', 28: 'GABRIELLA', 24: 'RIVKA', 4: 'SOPHIA', 5: 'ESTHER', 27: 'SOPHIE', 22: 'LILY', 10: 'MIRIAM', 8: 'AVA', 9: 'CHANA', 13: 'MIA', 6: 'RACHEL', 17: 'MAYA', 31: 'AVERY', 11: 'ELLA', 23: 'SOFIA', 3: 'SARAH', 21: 'VICTORIA', 16: 'ISABELLA', 2: 'LEAH', 15: 'CHARLOTTE', 46: 'VIOLET', 47: 'NATALIE', 69: 'LILIANA', 62: 'SURY', 71: 'SAVANNAH', 75: 'VERA', 72: 'VANESSA', 48: 'REBECCA', 77: 'SYLVIA', 67: 'TAYLOR', 57: 'VALENTINA', 73: 'SIMONE', 79: 'SHAINA', 53: 'RILEY', 64: 'YIDES', 78: 'SIMA', 51: 'NINA', 74: 'SLOANE', 63: 'NAOMI', 70: 'YAEL', 55: 'SYDNEY', 68: 'ZOEY', 76: 'YEHUDIS', 60: 'FRANCESCA', 49: 'MARIA', 61: 'ZISSY', 65: 'SKYLAR', 59: 'JOSEPHINE', 66: 'VERONICA', 50: 'YITTY', 58: 'TALIA', 52: 'KATHERINE', 54: 'SIENNA', 56: 'VIVIENNE', 81: 'YITTA', 83: 'YARA', 82: 'TZIVIA', 80: 'TZIPORA'}
YARA
TZIVIA
YITTA
TZIPORA
SHAINA
SIMA
SYLVIA
YEHUDIS
VERA
SLOANE

In [76]:
names=female_baby_names_2012
# Safely print rank 7 from the names dictionary
print(names[7])

# Safely print the type of rank 100 from the names dictionary
print(type(names.get(100)))

# Safely print rank 105 from the names dictionary or 'Not Found'
print( names.get(105,'Not Found' ))

CHAYA
<class 'NoneType'>
Not Found

In [79]:
d = (map( lambda year :{year: dict(zip(records[records['BRITH_YEAR']==year].RANK, records[records['BRITH_YEAR']==year].NAME))}, records[records['GENDER']=='MALE'].BRITH_YEAR))

In [128]:
boy_names = {year: dict(zip(records[(records['BRITH_YEAR']==year) & (records['GENDER']=='MALE')].RANK, records[(records['BRITH_YEAR']==year) & (records['GENDER']=='MALE')].NAME)) for year in records.BRITH_YEAR.unique()}
#boy_names

In [129]:

# Print a list of keys from the boy_names dictionary
print(boy_names.keys())

# Print a list of keys from the boy_names dictionary for the year 2013
print(boy_names[2013].keys())

# Loop over the dictionary
for year in boy_names:
    # Safely print the year and the third ranked name or 'Unknown'
    print(year, boy_names[year].get(3, 'Unknown'))

dict_keys([2011, 2012, 2013, 2014])
dict_keys([50, 13, 54, 47, 49, 32, 44, 56, 42, 5, 43, 45, 24, 16, 30, 25, 57, 19, 51, 37, 55, 33, 21, 36, 53, 38, 7, 52, 40, 27, 35, 8, 2, 14, 34, 46, 29, 22, 9, 1, 28, 48, 26, 11, 31, 23, 10, 39, 4, 41, 17, 12, 6, 20, 18, 3, 15, 62, 61, 60, 59, 58, 79, 82, 95, 94, 90, 73, 85, 92, 65, 93, 81, 69, 76, 74, 87, 67, 88, 84, 83, 63, 86, 91, 89, 71, 66, 68, 75, 78, 80, 64, 70, 72, 77, 96, 100, 99, 97, 98])
2011 JACOB
2012 MICHAEL
2013 MICHAEL
2014 MICHAEL

In [130]:
names_2010=None
# Assign the names_2011 dictionary as the value to the 2010 key of boy_names
boy_names[2010] = names_2010

# Update the 2012 key in the boy_names dictionary
boy_names[2012].update([(1,'Casey'), (2,'Aiden')])

# Loop over the years in the boy_names dictionary 
for year in boy_names:
    # Sort the data for each year by descending rank and get the lowest one
    lowest_ranked =  sorted(boy_names[year], reverse=True)[0]
    # Safely print the year and the least popular name or 'Not Available'
    print(year, boy_names[year].get(lowest_ranked,'Not Available'))

2011 YONAH
2012 YARIEL
2013 YITZCHAK
2014 YIDEL

TypeError: 'NoneType' object is not iterable

In [131]:
female_names = {year: dict(zip(records[(records['BRITH_YEAR']==year) & (records['GENDER']=='FEMALE')].RANK, records[(records['BRITH_YEAR']==year) & (records['GENDER']=='FEMALE')].NAME)) for year in records.BRITH_YEAR.unique()}
# Remove 2011 from female_names and store it: female_names_2011
female_names_2011 = female_names.pop(2011)

# Safely remove 2015 from female_names with an empty dictionary as the default: female_names_2015
female_names_2015 = female_names.pop(2015, {})

# Delete 2012 from female_names
del female_names[2012]
# Print female_names
print(female_names)

{2013: {37: 'VIOLET', 18: 'EMILY', 42: 'NORA', 34: 'STELLA', 26: 'ZOE', 41: 'SAMANTHA', 17: 'RIVKA', 20: 'VICTORIA', 40: 'AVERY', 25: 'JULIA', 30: 'GABRIELLA', 33: 'RAIZY', 36: 'PENELOPE', 7: 'RACHEL', 24: 'ELIZABETH', 39: 'MADELINE', 27: 'LILY', 11: 'ISABELLA', 21: 'ANNA', 32: 'SOPHIE', 28: 'MADISON', 29: 'GITTY', 35: 'RIVKY', 31: 'MALKA', 38: 'SADIE', 2: 'EMMA', 19: 'HANNAH', 4: 'SOPHIA', 5: 'SARAH', 16: 'SOFIA', 15: 'ELLA', 9: 'MIRIAM', 12: 'CHARLOTTE', 6: 'LEAH', 22: 'ABIGAIL', 23: 'CHLOE', 8: 'CHAYA', 3: 'ESTHER', 13: 'MIA', 1: 'OLIVIA', 14: 'SARA', 10: 'CHANA', 46: 'SIENNA', 45: 'SCARLETT', 44: 'CATHERINE', 47: 'VIVIAN', 43: 'TOBY', 78: 'YASMIN', 72: 'ZISSY', 75: 'SHIFRA', 71: 'SKYLAR', 76: 'TZIPORA', 77: 'YAEL', 58: 'VALENTINA', 64: 'YOCHEVED', 69: 'MALAK', 70: 'VALERIE', 74: 'WILLA', 48: 'ROSE', 52: 'TALIA', 57: 'LEILA', 55: 'EMILIA', 61: 'PEARL', 67: 'MARGARET', 73: 'YIDES', 66: 'HENNY', 65: 'SURY', 59: 'CLAIRE', 68: 'ZOEY', 60: 'JULIET', 62: 'MICHELLE', 51: 'NINA', 56: 'VIVIENNE', 53: 'YITTY', 63: 'PESSY', 54: 'ROCHEL', 50: 'ANGELINA', 49: 'REBECCA', 81: 'ZELDA', 80: 'TESSA', 82: 'TRANY', 79: 'SURI'}, 2014: {40: 'YITTY', 23: 'GABRIELLA', 19: 'ELIZABETH', 32: 'NORA', 31: 'AMELIA', 33: 'MADISON', 39: 'VIVIAN', 26: 'RAIZY', 38: 'MILA', 10: 'MIRIAM', 35: 'ELEANOR', 28: 'CHLOE', 18: 'MAYA', 34: 'AVERY', 5: 'EMMA', 12: 'CHARLOTTE', 37: 'PENELOPE', 36: 'HANNAH', 20: 'RIVKA', 24: 'LILY', 22: 'ANNA', 17: 'SOFIA', 15: 'ISABELLA', 21: 'ZOE', 2: 'ESTHER', 25: 'GRACE', 9: 'AVA', 30: 'FAIGY', 11: 'MIA', 27: 'VICTORIA', 4: 'LEAH', 3: 'RACHEL', 13: 'ABIGAIL', 7: 'SARAH', 29: 'STELLA', 8: 'SOPHIA', 14: 'SARA', 6: 'CHAYA', 1: 'OLIVIA', 16: 'ELLA', 41: 'LUCY', 73: 'SYDNEY', 44: 'SHAINDY', 65: 'SURY', 63: 'MARGARET', 66: 'PESSY', 57: 'JOSEPHINE', 71: 'ZISSY', 52: 'SIENNA', 70: 'ZOEY', 64: 'JULIETTE', 69: 'PHOEBE', 53: 'SADIE', 62: 'HINDY', 67: 'MINDY', 68: 'YOCHEVED', 56: 'SCARLETT', 50: 'TOBY', 49: 'DEVORAH', 72: 'TAYLOR', 55: 'NINA', 60: 'VIVIENNE', 61: 'MADELEINE', 51: 'VALENTINA', 45: 'EMILIA', 58: 'GIANNA', 54: 'LILA', 46: 'RIVKY', 43: 'SOPHIE', 59: 'CATHERINE', 42: 'SAMANTHA', 47: 'VIOLET', 48: 'RUBY', 84: 'ZELDA', 74: 'SIMONE', 77: 'SHOSHANA', 85: 'YASMINA', 86: 'SYLVIE', 83: 'TESSA', 78: 'VERONICA', 76: 'LOLA', 79: 'SKYLAR', 82: 'TZIPORA', 81: 'SHAINDEL', 80: 'YAEL', 75: 'SHIFRA'}}

In [ ]:
#checking dict for data
# .get() does a lot of work to check for a key
# in operator is much more efficient and clear

In [135]:
# Iterate over the 2014 nested dictionary
for rank, name in boy_names[2014].items():
    # Print rank and name
    print(rank, name)
    
# Iterate over the 2012 nested dictionary
for rank, name in boy_names[2012].items():
    # Print rank and name
    print(rank, name)
    # Print rank and name

54 ARON
14 HENRY
58 MILES
38 ANDREW
33 ELI
42 JACKSON
51 YITZCHOK
56 LEVI
57 SHMUEL
39 ZACHARY
5 JACOB
40 OWEN
48 ASHER
26 LUCAS
21 NOAH
50 ROBERT
47 JONATHAN
55 MARK
36 MASON
29 ANTHONY
45 AIDEN
37 MORDECHAI
53 CHRISTIAN
18 ETHAN
52 GEORGE
24 THEODORE
34 SHIMON
30 OLIVER
7 ALEXANDER
46 CHRISTOPHER
22 MATTHEW
9 SAMUEL
2 DAVID
11 JAMES
35 LUKE
28 YOSEF
44 NATHAN
20 RYAN
10 JACK
1 JOSEPH
49 LOGAN
32 GABRIEL
17 JOHN
15 ABRAHAM
19 LIAM
16 NICHOLAS
4 MOSHE
13 WILLIAM
12 ADAM
27 THOMAS
6 BENJAMIN
23 CHAIM
41 YEHUDA
31 MAX
3 MICHAEL
25 ISAAC
8 DANIEL
43 YISROEL
59 SHLOMO
60 PETER
90 NAFTALI
75 SHIA
98 YISRAEL
88 YOUSSEF
74 OSCAR
84 PHILIP
93 SHMIEL
95 NAFTULI
68 YAKOV
96 YUSUF
89 SIMCHA
91 RONAN
78 TYLER
72 EDWARD
92 USHER
69 HUNTER
85 TIMOTHY
80 SAM
82 IAN
94 YOUSEF
66 NATHANIEL
87 XAVIER
97 YOSSI
73 YECHIEL
67 YAAKOV
86 YEHOSHUA
81 SHAYA
70 VINCENT
79 WYATT
61 SEAN
64 GAVIN
83 RAPHAEL
65 ZEV
62 ELIEZER
76 LEONARDO
77 VICTOR
63 SOLOMON
71 ARI
100 YOEL
101 YAHYA
99 SHEA
102 YIDEL
61 COLIN
19 ANTHONY
58 ZEV
55 TYLER
43 JONATHAN
32 AARON
60 PETER
44 LUCA
56 MENDEL
34 MORDECHAI
6 DANIEL
38 JOSHUA
53 MAXWELL
24 ANDREW
16 WILLIAM
54 SHLOMO
57 YAAKOV
29 LUKE
23 LUCAS
46 OWEN
50 NATHANIEL
59 MARK
18 CHARLES
52 SIMON
28 ZACHARY
35 THEODORE
49 JONAH
48 YAKOV
9 SAMUEL
45 JULIAN
33 SHIMON
14 RYAN
41 GEORGE
5 MOSHE
2 Aiden
13 NICHOLAS
39 ROBERT
30 MASON
42 SEBASTIAN
17 ADAM
27 MAX
31 ELI
8 BENJAMIN
22 THOMAS
40 NATHAN
26 OLIVER
4 JACOB
10 JAMES
20 LIAM
3 MICHAEL
36 YISROEL
21 NOAH
12 CHAIM
37 YEHUDA
7 ALEXANDER
47 YITZCHOK
25 YOSEF
51 LEVI
1 Casey
15 JOHN
11 JACK
99 WILSON
86 SPENCER
91 YOUSEF
65 ARI
94 ZAIN
85 SHLOME
66 TZVI
84 RAYMOND
96 VINCENT
88 SHLOIMY
98 WESLEY
95 YAEL
74 MAXIMILIAN
92 ZALMEN
79 SHIA
62 CONNOR
100 YARIEL
93 YOUSSEF
87 NACHMAN
73 VICTOR
97 ZAYDEN
68 SOLOMON
77 USHER
89 XAVIER
67 KEVIN
81 YOEL
63 ALI
82 YEHOSHUA
71 MARTIN
80 TIMOTHY
90 YUSUF
75 TRISTAN
69 SIMCHA
76 YECHIEL
64 VINCENT
78 SHAYA
83 LORENZO
72 PATRICK
70 ELIAS

In [136]:
# Check to see if 2011 is in baby_names
if 2011 in boy_names.keys():
    # Print 'Found 2011'
    print('Found 2011')
    
# Check to see if rank 1 is in 2012
if 1  in boy_names[2012]:
    # Print 'Found Rank 1 in 2012' if found
    print('Found Rank 1 in 2012')
else:
    # Print 'Rank 1 missing from 2012' if not found
    print('Rank 1 missing from 2012')
    
# Check to see if Rank 5 is in 2013
if 1 in boy_names[2013]:
   # Print 'Found Rank 5'
   print('Found Rank 5')

Found 2011
Found Rank 1 in 2012
Found Rank 5

In [ ]:
#import csv

In [141]:
# Import the python CSV module
import csv
baby_names={}
# Create a python file object in read mode for the baby_names.csv file: csvfile
csvfile = open('../datasets/baby_names.csv','r')

# Loop over a csv reader on the file object
for row in csv.reader(csvfile):
    # Print each row 
    print(row)
    # Add the rank and name to the dictionary
    baby_names[row[5]] = row[3]

# Print the dictionary keys
print(baby_names.keys())

PANIC', 'Austin', '40', '72']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Avi', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Avraham', '55', '59']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Avrohom', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Avrum', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Axel', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ayden', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Aydin', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Baruch', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Beckett', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ben', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Benjamin', '233', '6']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Bennett', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Benzion', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Berish', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Berl', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Binyamin', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Binyomin', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Blake', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Boruch', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brady', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brandon', '33', '79']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brayden', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brendan', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brian', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brody', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Brooks', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Caleb', '28', '84']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Calvin', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Cameron', '24', '88']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Carter', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Chaim', '130', '23']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Charles', '131', '22']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Charlie', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Chase', '43', '70']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Cheskel', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Christian', '64', '53']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Christopher', '76', '46']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Cole', '31', '81']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Colin', '36', '76']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Connor', '43', '70']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Conor', '19', '93']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Cooper', '40', '72']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Cormac', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Damian', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Daniel', '223', '8']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dante', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dashiell', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'David', '272', '2']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dean', '19', '93']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Declan', '43', '70']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Denis', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Derek', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Devin', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dominic', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dominick', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dov', '38', '74']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dovid', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Drew', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Duvid', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Dylan', '94', '36']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Edward', '40', '72']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Efraim', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Eitan', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Eli', '103', '33']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Elias', '32', '80']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Eliezer', '52', '62']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Elijah', '28', '84']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Elimelech', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Eliyahu', '25', '87']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Elliot', '33', '79']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Elliott', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ellis', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Emmett', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Eric', '29', '83']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Erik', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ethan', '149', '18']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Evan', '58', '56']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Everett', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ezra', '45', '68']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Felix', '32', '80']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Filip', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Finn', '21', '91']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Francesco', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Francis', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Frank', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Frederick', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Gabriel', '105', '32']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Gavin', '50', '64']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Gavriel', '17', '95']
['2014', 'MALE', 'WHITE NON HISPANIC', 'George', '65', '52']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Giovanni', '32', '80']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Giuseppe', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Graham', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Grant', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Grayson', '30', '82']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Gregory', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Greyson', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Griffin', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hamza', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Harrison', '44', '69']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Harry', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hayden', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Henry', '176', '14']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hersh', '22', '90']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hershel', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hershy', '21', '91']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hillel', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hudson', '58', '56']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hugo', '22', '90']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Hunter', '44', '69']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ian', '30', '82']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ibrahim', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Imran', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Isaac', '125', '25']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Israel', '35', '77']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Issac', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ivan', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jace', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jack', '199', '10']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jackson', '85', '42']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jacob', '256', '5']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jake', '46', '67']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jakub', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'James', '195', '11']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jason', '49', '65']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jasper', '24', '88']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jax', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jaxon', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jaxson', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jayden', '35', '77']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jeremy', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jesse', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Joel', '31', '81']
['2014', 'MALE', 'WHITE NON HISPANIC', 'John', '158', '17']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jonah', '45', '68']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jonathan', '75', '47']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jordan', '34', '78']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Joseph', '300', '1']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Joshua', '68', '49']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Judah', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Jude', '25', '87']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Julian', '87', '40']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Justin', '24', '88']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Kai', '23', '89']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Karas', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Kareem', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Kevin', '17', '95']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Kieran', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Kyle', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Landon', '23', '89']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lazer', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Leibish', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Leo', '108', '31']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Leon', '32', '80']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Leonardo', '36', '76']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lev', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Levi', '58', '56']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Liam', '139', '19']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lincoln', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lipa', '39', '73']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Logan', '68', '49']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lorenzo', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Louis', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Luca', '94', '36']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lucas', '121', '26']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lucien', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Luka', '24', '88']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Lukas', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Luke', '99', '35']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Marc', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Marcel', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Marco', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Marcus', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mark', '61', '55']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Martin', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mason', '94', '36']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mateo', '21', '91']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Matteo', '22', '90']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Matthew', '131', '22']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Max', '108', '31']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Maxim', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Maximilian', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Maximus', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Maxwell', '45', '68']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mayer', '29', '83']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Meilech', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Meir', '66', '51']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Menachem', '118', '27']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Menashe', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mendel', '38', '74']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mendy', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Micah', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Michael', '268', '3']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Milan', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Miles', '56', '58']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Milo', '28', '84']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mohamed', '49', '65']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mohammed', '22', '90']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Moishe', '21', '91']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mordche', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Mordechai', '92', '37']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Morris', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Moses', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Moshe', '267', '4']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Muhammad', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Myles', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Naftali', '22', '90']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Naftuli', '17', '95']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nathan', '82', '44']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nathaniel', '47', '66']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nicholas', '166', '16']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nico', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nicolas', '32', '80']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nikita', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Noah', '137', '21']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Noam', '23', '89']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nolan', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Nosson', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Oliver', '109', '30']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Omar', '49', '65']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Oscar', '38', '74']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Owen', '87', '40']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Parker', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Patrick', '49', '65']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Paul', '25', '87']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Peter', '54', '60']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Philip', '28', '84']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Pinchas', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Pinchus', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Preston', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Quinn', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Rafael', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Raphael', '29', '83']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Rayan', '21', '91']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Raymond', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Reed', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Reid', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Reuben', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Rhys', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Richard', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Riley', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Robert', '67', '50']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Rocco', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Roman', '35', '77']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ronan', '21', '91']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Rory', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Rowan', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ryan', '138', '20']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Ryder', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Salvatore', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Sam', '32', '80']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Samir', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Samuel', '206', '9']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Santino', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Sawyer', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Sean', '53', '61']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Sebastian', '100', '34']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shalom', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shane', '19', '93']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shaya', '31', '81']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shea', '13', '99']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shia', '37', '75']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shimon', '100', '34']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shloime', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shloimy', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shlome', '19', '93']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shlomo', '55', '59']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shmiel', '19', '93']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shmuel', '57', '57']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Sholom', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shraga', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Shulem', '45', '68']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Silas', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Simcha', '23', '89']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Simon', '49', '65']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Solomon', '51', '63']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Spencer', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Stephen', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Steven', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Theo', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Theodore', '126', '24']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Thomas', '118', '27']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Timothy', '27', '85']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Tristan', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Tyler', '34', '78']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Tzvi', '49', '65']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Usher', '20', '92']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Victor', '35', '77']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Vincent', '43', '70']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Vincenzo', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Wesley', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Weston', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'William', '183', '13']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Winston', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Wolf', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Wyatt', '33', '79']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Xavier', '25', '87']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yaakov', '46', '67']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yahya', '11', '101']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yakov', '45', '68']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yaseen', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yechiel', '39', '73']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yehoshua', '26', '86']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yehuda', '86', '41']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yidel', '10', '102']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yisrael', '14', '98']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yisroel', '83', '43']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yitzchak', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yitzchok', '66', '51']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yoel', '12', '100']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yosef', '116', '28']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yossi', '15', '97']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yousef', '18', '94']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Youssef', '24', '88']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Yusuf', '16', '96']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Zachary', '90', '39']
['2014', 'MALE', 'WHITE NON HISPANIC', 'Zev', '49', '65']
dict_keys(['RANK', '75', '67', '42', '51', '53', '62', '8', '74', '71', '78', '73', '72', '77', '60', '1', '70', '61', '65', '58', '41', '76', '68', '48', '55', '40', '66', '64', '34', '44', '57', '63', '33', '31', '20', '69', '35', '13', '52', '59', '39', '9', '27', '10', '56', '12', '2', '25', '18', '14', '38', '28', '6', '3', '19', '45', '47', '11', '79', '17', '43', '80', '37', '81', '46', '5', '22', '50', '21', '30', '24', '54', '15', '36', '23', '7', '16', '49', '29', '4', '32', '26', '92', '90', '82', '91', '88', '89', '94', '83', '93', '84', '87', '85', '86', '96', '97', '95', '99', '98', '100', '101', '102'])

In [144]:
# Import the python CSV module
import csv
baby_names={}
# Create a python file object in read mode for the `baby_names.csv` file: csvfile
csvfile = open('../datasets/baby_names.csv', 'r')

# Loop over a DictReader on the file
for row in csv.DictReader(csvfile):
    # Print each row 
    print(row)
    # Add the rank and name to the dictionary: baby_names
    baby_names[row['RANK']] = row['NAME']

# Print the dictionary keys
print(baby_names.keys())

R': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Lincoln', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Lipa', 'COUNT': '39', 'RANK': '73'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Logan', 'COUNT': '68', 'RANK': '49'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Lorenzo', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Louis', 'COUNT': '18', 'RANK': '94'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Luca', 'COUNT': '94', 'RANK': '36'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Lucas', 'COUNT': '121', 'RANK': '26'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Lucien', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Luka', 'COUNT': '24', 'RANK': '88'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Lukas', 'COUNT': '27', 'RANK': '85'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Luke', 'COUNT': '99', 'RANK': '35'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Marc', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Marcel', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Marco', 'COUNT': '15', 'RANK': '97'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Marcus', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mark', 'COUNT': '61', 'RANK': '55'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Martin', 'COUNT': '26', 'RANK': '86'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mason', 'COUNT': '94', 'RANK': '36'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mateo', 'COUNT': '21', 'RANK': '91'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Matteo', 'COUNT': '22', 'RANK': '90'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Matthew', 'COUNT': '131', 'RANK': '22'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Max', 'COUNT': '108', 'RANK': '31'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Maxim', 'COUNT': '26', 'RANK': '86'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Maximilian', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Maximus', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Maxwell', 'COUNT': '45', 'RANK': '68'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mayer', 'COUNT': '29', 'RANK': '83'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Meilech', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Meir', 'COUNT': '66', 'RANK': '51'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Menachem', 'COUNT': '118', 'RANK': '27'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Menashe', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mendel', 'COUNT': '38', 'RANK': '74'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mendy', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Micah', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Michael', 'COUNT': '268', 'RANK': '3'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Milan', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Miles', 'COUNT': '56', 'RANK': '58'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Milo', 'COUNT': '28', 'RANK': '84'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mohamed', 'COUNT': '49', 'RANK': '65'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mohammed', 'COUNT': '22', 'RANK': '90'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Moishe', 'COUNT': '21', 'RANK': '91'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mordche', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Mordechai', 'COUNT': '92', 'RANK': '37'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Morris', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Moses', 'COUNT': '26', 'RANK': '86'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Moshe', 'COUNT': '267', 'RANK': '4'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Muhammad', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Myles', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Naftali', 'COUNT': '22', 'RANK': '90'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Naftuli', 'COUNT': '17', 'RANK': '95'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nathan', 'COUNT': '82', 'RANK': '44'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nathaniel', 'COUNT': '47', 'RANK': '66'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nicholas', 'COUNT': '166', 'RANK': '16'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nico', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nicolas', 'COUNT': '32', 'RANK': '80'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nikita', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Noah', 'COUNT': '137', 'RANK': '21'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Noam', 'COUNT': '23', 'RANK': '89'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nolan', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Nosson', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Oliver', 'COUNT': '109', 'RANK': '30'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Omar', 'COUNT': '49', 'RANK': '65'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Oscar', 'COUNT': '38', 'RANK': '74'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Owen', 'COUNT': '87', 'RANK': '40'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Parker', 'COUNT': '27', 'RANK': '85'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Patrick', 'COUNT': '49', 'RANK': '65'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Paul', 'COUNT': '25', 'RANK': '87'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Peter', 'COUNT': '54', 'RANK': '60'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Philip', 'COUNT': '28', 'RANK': '84'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Pinchas', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Pinchus', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Preston', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Quinn', 'COUNT': '14', 'RANK': '98'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Rafael', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Raphael', 'COUNT': '29', 'RANK': '83'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Rayan', 'COUNT': '21', 'RANK': '91'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Raymond', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Reed', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Reid', 'COUNT': '15', 'RANK': '97'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Reuben', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Rhys', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Richard', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Riley', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Robert', 'COUNT': '67', 'RANK': '50'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Rocco', 'COUNT': '15', 'RANK': '97'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Roman', 'COUNT': '35', 'RANK': '77'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Ronan', 'COUNT': '21', 'RANK': '91'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Rory', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Rowan', 'COUNT': '15', 'RANK': '97'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Ryan', 'COUNT': '138', 'RANK': '20'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Ryder', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Salvatore', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Sam', 'COUNT': '32', 'RANK': '80'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Samir', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Samuel', 'COUNT': '206', 'RANK': '9'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Santino', 'COUNT': '14', 'RANK': '98'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Sawyer', 'COUNT': '27', 'RANK': '85'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Sean', 'COUNT': '53', 'RANK': '61'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Sebastian', 'COUNT': '100', 'RANK': '34'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shalom', 'COUNT': '14', 'RANK': '98'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shane', 'COUNT': '19', 'RANK': '93'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shaya', 'COUNT': '31', 'RANK': '81'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shea', 'COUNT': '13', 'RANK': '99'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shia', 'COUNT': '37', 'RANK': '75'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shimon', 'COUNT': '100', 'RANK': '34'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shloime', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shloimy', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shlome', 'COUNT': '19', 'RANK': '93'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shlomo', 'COUNT': '55', 'RANK': '59'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shmiel', 'COUNT': '19', 'RANK': '93'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shmuel', 'COUNT': '57', 'RANK': '57'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Sholom', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shraga', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Shulem', 'COUNT': '45', 'RANK': '68'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Silas', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Simcha', 'COUNT': '23', 'RANK': '89'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Simon', 'COUNT': '49', 'RANK': '65'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Solomon', 'COUNT': '51', 'RANK': '63'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Spencer', 'COUNT': '18', 'RANK': '94'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Stephen', 'COUNT': '18', 'RANK': '94'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Steven', 'COUNT': '27', 'RANK': '85'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Theo', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Theodore', 'COUNT': '126', 'RANK': '24'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Thomas', 'COUNT': '118', 'RANK': '27'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Timothy', 'COUNT': '27', 'RANK': '85'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Tristan', 'COUNT': '26', 'RANK': '86'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Tyler', 'COUNT': '34', 'RANK': '78'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Tzvi', 'COUNT': '49', 'RANK': '65'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Usher', 'COUNT': '20', 'RANK': '92'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Victor', 'COUNT': '35', 'RANK': '77'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Vincent', 'COUNT': '43', 'RANK': '70'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Vincenzo', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Wesley', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Weston', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'William', 'COUNT': '183', 'RANK': '13'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Winston', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Wolf', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Wyatt', 'COUNT': '33', 'RANK': '79'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Xavier', 'COUNT': '25', 'RANK': '87'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yaakov', 'COUNT': '46', 'RANK': '67'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yahya', 'COUNT': '11', 'RANK': '101'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yakov', 'COUNT': '45', 'RANK': '68'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yaseen', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yechiel', 'COUNT': '39', 'RANK': '73'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yehoshua', 'COUNT': '26', 'RANK': '86'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yehuda', 'COUNT': '86', 'RANK': '41'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yidel', 'COUNT': '10', 'RANK': '102'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yisrael', 'COUNT': '14', 'RANK': '98'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yisroel', 'COUNT': '83', 'RANK': '43'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yitzchak', 'COUNT': '15', 'RANK': '97'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yitzchok', 'COUNT': '66', 'RANK': '51'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yoel', 'COUNT': '12', 'RANK': '100'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yosef', 'COUNT': '116', 'RANK': '28'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yossi', 'COUNT': '15', 'RANK': '97'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yousef', 'COUNT': '18', 'RANK': '94'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Youssef', 'COUNT': '24', 'RANK': '88'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Yusuf', 'COUNT': '16', 'RANK': '96'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Zachary', 'COUNT': '90', 'RANK': '39'}
{'BRITH_YEAR': '2014', 'GENDER': 'MALE', 'ETHNICTY': 'WHITE NON HISPANIC', 'NAME': 'Zev', 'COUNT': '49', 'RANK': '65'}
dict_keys(['75', '67', '42', '51', '53', '62', '8', '74', '71', '78', '73', '72', '77', '60', '1', '70', '61', '65', '58', '41', '76', '68', '48', '55', '40', '66', '64', '34', '44', '57', '63', '33', '31', '20', '69', '35', '13', '52', '59', '39', '9', '27', '10', '56', '12', '2', '25', '18', '14', '38', '28', '6', '3', '19', '45', '47', '11', '79', '17', '43', '80', '37', '81', '46', '5', '22', '50', '21', '30', '24', '54', '15', '36', '23', '7', '16', '49', '29', '4', '32', '26', '92', '90', '82', '91', '88', '89', '94', '83', '93', '84', '87', '85', '86', '96', '97', '95', '99', '98', '100', '101', '102'])